### ISSUE TITLE
Python Binding dbscan.DBSCAN Error

### ISSUE THREAD

**Issue by mohammedsalah98** [wangyiqiu/dbscan-python#11]
Hello,

I am trying to implement the library on python. Did the installation using pip3 install dbscan and I get this error:
ModuleNotFoundError: No module named 'dbscan.DBSCAN'
I am using python 3.9.12.

Thanks for the help.

**Comment by wangyiqiu** [comment]
Hi we are still fixing the binary in PyPI. Will get back to you once it is done. For now, please try to use the binary executable. Sorry about the inconvenience.

**Comment by anivegesana** [comment]
@mohammedsalah98 For now, if you REALLY are bottlenecked and are using either x86-64 Linux or x86-64 Mac, you can use the wheels that I compiled for Python 3.9 from a development branch of this repo from the artifacts link on [this page](https://github.com/anivegesana/dbscan-python/actions/runs/3519626421). @wangyiqiu is working on getting the library to work on Windows and ARM, so if you are using Windows or a Mac from the last two years or so, you have to wait.

Things might change in the future and you might need to do a `pip install --force-reinstall dbscan` in order to get the real 0.0.10 when it comes out. This is because that link was mainly for testing and is not really production ready, so I didn't fully figure out how to get setuptools_scm to work to adjust the versions on the CI built wheels. As @wangyiqiu suggested, I would recommend waiting and just use the executable, but I would like to give the option if you need it.

**Comment by wangyiqiu** [comment]
Hi @mohammedsalah98 
@anivegesana and I have fixed this issue. Please checkout v0.0.11 from PyPI or the updated master branch.
