### ISSUE TITLE
ST-DBSCAN extension possible?

### ISSUE THREAD

**Issue by jacksongoode** [wangyiqiu/dbscan-python#15]
I was wondering if this implementation could be extended to deal with spatio-temporal data (allowing one to specify a threshold for both space and time eps)?

**Comment by wangyiqiu** [comment]
It looks like the change is non-trivial, as it's not possible to just call DBSCAN as a subroutine to ST-DBSCAN.
The DBSCAN code here is quite involved so it may take some time. We will make a note but there's no guarantee when it can be added. So I encourage you to look on the internet for an ST-DBSCAN package.

**Comment by jacksongoode** [comment]
Thank you for your response. I guess the change I was imagining is allowing epsilon to be specified for each additional dimension added. In this case both space and time would be clustered by some value. I think st-dbscan goes further than just this however. You would know better than me! Best of luck!

**Comment by wangyiqiu** [comment]
Yeah, I looked into it for a while, and realized that the additional dimension for time may or may not involve density (I am not entirely sure about this). The Euclidean DBSCAN we implemented uses a spatial data structure for the range search of size epsilon, and because the shape of the search is spherical, there doesn't seem to be an easy way use a different epsilon for each dimension.
