### ISSUE TITLE
pypi module not working

### ISSUE THREAD

**Issue by nikisalli** [wangyiqiu/dbscan-python#2]
hello, the compiled module works like a charm but the module from pypi fails to load the DBSCAN method with error:
cannot import name 'DBSCAN' from 'dbscan' (unknown location)

awesome work btw

**Comment by wangyiqiu** [comment]
Thanks for your feedback. The module from pypi is kind of experimental at the moment, since we have only pre-compiled the library for Linux on x86_64. But we plan to extend it to support more computing environments in the near future.

May I know your computing environment? (e.g. architecture and operating system)
Thank you.

**Comment by nikisalli** [comment]
it is arch linux on x86 using python 3.9.6

it looks like it fails to load the module but the path is in fact correct:
```
$ python -c "import dbscan"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nik/.local/lib/python3.9/site-packages/dbscan/__init__.py", line 22, in <module>
    from dbscan.DBSCAN import DBSCAN
ModuleNotFoundError: No module named 'dbscan.DBSCAN'

$ ls /home/nik/.local/lib/python3.9/site-packages/dbscan
DBSCAN.cpython-38-x86_64-linux-gnu.so  example.py  __init__.py  __pycache__
```

if I change line 22 from `from dbscan.DBSCAN import DBSCAN` to `from dbscan import DBSCAN` the error changes to a circular import so my guess is that __init__.py tries to import the precompiled DBSCAN module and this tries to import __init__.py
